version: '3.8'

services:
  init:
    image: alpine:3.17
    command: sysctl -w net.ipv4.conf.all.src_valid_mark=1
    privileged: true

  main:
    build: .
    depends_on:
      - init
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
