version: '3.8'

services:
  mullvad-docker-proxy:
    image: ghcr.io/theboatymcboatface/mullvad-docker-proxy:latest
    container_name: mullvad-docker-proxy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PRIVATE_KEY=your_private_key_here
    ports:
      - "3128:3128"
    networks:
      - default

networks:
  default:
